services:
  client:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - client_node_modules:/app/node_modules
    working_dir: /app

volumes:
  client_node_modules:
  pnpm_store:

networks:
  default:
    name: inventory-network
    external: true
